# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: definitions/demo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'definitions/demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x65\x66initions/demo.proto\x12\x10\x64\x65\x66initions.demo\"\x1c\n\x0b\x44\x65moRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1f\n\x0c\x44\x65moResponse\x12\x0f\n\x07is_true\x18\x01 \x01(\x08\"8\n\x10MyServiceRequest\x12\x11\n\tvalue_one\x18\x01 \x01(\x05\x12\x11\n\tvalue_two\x18\x02 \x01(\x05\"E\n\x11MyServiceResponse\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x12\x0f\n\x07product\x18\x02 \x01(\x05\x12\x12\n\ndifference\x18\x03 \x01(\x05\x32V\n\x0b\x44\x65moService\x12G\n\x06IsTrue\x12\x1d.definitions.demo.DemoRequest\x1a\x1e.definitions.demo.DemoResponse2\xc0\x01\n\tMyService\x12W\n\x0cMyServiceApi\x12\".definitions.demo.MyServiceRequest\x1a#.definitions.demo.MyServiceResponse\x12Z\n\x0fSecondMyService\x12#.definitions.demo.MyServiceResponse\x1a\".definitions.demo.MyServiceRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'definitions.demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEMOREQUEST']._serialized_start=44
  _globals['_DEMOREQUEST']._serialized_end=72
  _globals['_DEMORESPONSE']._serialized_start=74
  _globals['_DEMORESPONSE']._serialized_end=105
  _globals['_MYSERVICEREQUEST']._serialized_start=107
  _globals['_MYSERVICEREQUEST']._serialized_end=163
  _globals['_MYSERVICERESPONSE']._serialized_start=165
  _globals['_MYSERVICERESPONSE']._serialized_end=234
  _globals['_DEMOSERVICE']._serialized_start=236
  _globals['_DEMOSERVICE']._serialized_end=322
  _globals['_MYSERVICE']._serialized_start=325
  _globals['_MYSERVICE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
